# Generated by Django 4.2.1 on 2023-05-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.CharField(max_length=7, verbose_name='Цена вида протеза'),
        ),
    ]
